### ISSUE TITLE
Glue crawler not running on setup.py

### ISSUE THREAD

**Issue by edenduthie** [awslabs/aws-customer-churn-pipeline#15]
I ran the setup.py but I got this message:

```
An error occurred (EntityNotFoundException) when calling the StartCrawler operation: Crawler with name crawler-customer-churn-sagemaker-pipeline does not exist
```

I think there is some kind of race condition where it tries to run the crawler before it is created.

I went and ran the crawler manually and it worked.

**Comment by momonga-ml** [comment]
@sunbc0120  Do you have the bandwidth to address?

**Comment by sunbc0120** [comment]
I suspect an increase in the sleep time from 30 to 60 will do.

```bash
aws s3 sync ./cfn/ s3://${S3_BUCKET_NAME}/cfn/ > /dev/null

# need to wait for cloudformation to finish to kick off job
sleep 30  # here

aws glue --region ${REGION} start-crawler --name crawler-${STACK_NAME} > /dev/null
```

**Comment by sunbc0120** [comment]
@momonga-ml will check after my PC comes back to life.
